struct State
    truth_table::UInt8
end

struct T_NOT end
struct T_XOR end
struct T_AND end
struct T_OR end

const NOT = T_NOT()
const XOR = T_XOR()
const AND = T_AND()
const OR = T_OR()

operation(::T_NOT) = (~)
operation(::T_XOR) = (xor)
operation(::T_AND) = (&)
operation(::T_OR) = (|)
operation(::Nothing) = error("Cannot get the operation of 'nothing'. Likely tried to get the operation of a terminal node.")

struct Action
    op::Union{T_NOT, T_XOR, T_AND, T_OR, Nothing}
    arg1::UInt8
    arg2::UInt8 # unused for NOT
end
operation(a::Action) = operation(a.op)

function state_iterator(start::UInt8=UInt8(0))
    return start:UInt8(255)
end

"""Return the best action for a state (highest Q-value)."""
function best_action(state::State, Q, available_actions)
    actions = available_actions[state]
    best_a = first(actions)
    best_v = Q[(state, best_a)]
    for a in actions
        v = Q[(state, a)]
        if v > best_v
            best_v = v
            best_a = a
        end
    end
    return best_a
end

"""Recursively build a Julia Expr for the optimal formula by tracing back through the Q table."""
function build_rule_expr(state::State, Q, available_actions, terminal_state_values)
    a = best_action(state, Q, available_actions)

    # Terminal state: return the appropriate input symbol
    if a.op === nothing
        tt = state.truth_table
        tt == 0xf0 && return :l          # left input
        tt == 0xcc && return :c          # centre input
        tt == 0xaa && return :r          # right input
        tt == 0x00 && return :(zero(T))  # constant zero
        tt == 0xff && return :m          # mask (all N bits set)
        error("Unknown terminal state: 0x$(string(tt, base=16))")
    end

    sub1 = build_rule_expr(State(a.arg1), Q, available_actions, terminal_state_values)

    if a.op isa T_NOT
        return Expr(:call, :(~), sub1)
    end

    sub2 = build_rule_expr(State(a.arg2), Q, available_actions, terminal_state_values)

    op_sym = if a.op isa T_AND; :(&)
             elseif a.op isa T_OR;  :(|)
             elseif a.op isa T_XOR; :xor
             else error("Unknown op: $(a.op)")
             end

    return Expr(:call, op_sym, sub1, sub2)
end

"""Convert a body Expr to a formatted code string."""
function expr_to_string(expr)
    expr isa Symbol && return string(expr)
    (expr isa Expr && expr.head == :call) || return string(expr)

    op = expr.args[1]
    if op == :(~)
        return "~($(expr_to_string(expr.args[2])))"
    elseif op == :xor
        return "xor($(expr_to_string(expr.args[2])), $(expr_to_string(expr.args[3])))"
    elseif length(expr.args) == 3 # binary infix
        return "($(expr_to_string(expr.args[2])) $(op) $(expr_to_string(expr.args[3])))"
    else # generic call, e.g. zero(T)
        args = join(expr_to_string.(expr.args[2:end]), ", ")
        return "$(op)($(args))"
    end
end

"""Check whether an expression uses a particular input symbol (:l, :c, or :r)."""
function uses_input(expr, sym::Symbol)
    expr isa Symbol && return expr == sym
    expr isa Expr || return false
    return any(uses_input(a, sym) for a in expr.args[2:end])
end

"""Build a full @inline function Expr for a rule given its body expression."""
function make_apply_expr(rule::Int, body_expr)
    needs_l = uses_input(body_expr, :l)
    needs_c = uses_input(body_expr, :c)
    needs_r = uses_input(body_expr, :r)

    func_body = Expr(:block)
    push!(func_body.args, :(m = ~(~zero(T) << N)))
    needs_l && push!(func_body.args, :(l = shift_left(x, Val(N))))
    needs_c && push!(func_body.args, :(c = x))
    needs_r && push!(func_body.args, :(r = shift_right(x, Val(N))))
    push!(func_body.args, Expr(:return, Expr(:call, :(&), :m, body_expr)))

    sig = :(apply(::ECARule{$rule, N}, x::T) where {N, T})
    return Expr(:function, sig, func_body)
end

"""Write the generated rule functions to rules.jl."""
function write_rules_file(filename::String, body_exprs::Vector{Any})
    open(filename, "w") do io
        println(io, "# Auto-generated Elementary Cellular Automaton rule implementations")
        println(io, "# Generated by eca_dp.jl")
        println(io, "#")
        println(io, "# Each rule operates on a packed bit array x of type T with N active bits,")
        println(io, "# using periodic (circular) boundary conditions via shift_left / shift_right.")
        println(io, "#   l = shift_left(x)  — left neighbours  (cell i-1 for each cell i)")
        println(io, "#   c = x              — centre cells")
        println(io, "#   r = shift_right(x) — right neighbours (cell i+1 for each cell i)")
        println(io)

        # Rule type: dispatch on rule number R and bit count N
        println(io, "struct ECARule{R, N} end")
        println(io, "ECARule(rule::Int, nbits::Int) = ECARule{rule, nbits}()")
        println(io)

        # Periodic boundary shift functions
        println(io, "@inline function shift_left(x::T, ::Val{N}) where {T, N}")
        println(io, "    (x << 1) | (x >> (N - 1))")
        println(io, "end")
        println(io)
        println(io, "@inline function shift_right(x::T, ::Val{N}) where {T, N}")
        println(io, "    (x >> 1) | ((x & one(T)) << (N - 1))")
        println(io, "end")
        println(io)

        # One apply method per rule
        for (i, body_expr) in enumerate(body_exprs)
            rule = i - 1
            code = expr_to_string(body_expr)
            needs_l = uses_input(body_expr, :l)
            needs_c = uses_input(body_expr, :c)
            needs_r = uses_input(body_expr, :r)

            println(io, "# Rule $(rule): $(code)")
            println(io, "@inline function apply(::ECARule{$(rule), N}, x::T) where {N, T}")
            println(io, "    m = ~(~zero(T) << N)")
            needs_l && println(io, "    l = shift_left(x, Val(N))")
            needs_c && println(io, "    c = x")
            needs_r && println(io, "    r = shift_right(x, Val(N))")
            println(io, "    return m & ($(code))")
            println(io, "end")
            println(io)
        end

        # Verification function
        write_test_function(io)
    end

    println("Generated $(filename) with 256 ECA rule implementations")
end

function write_test_function(io)
    println(io, "\"\"\"")
    println(io, "    test_all_rules(n=8) → Bool")
    println(io)
    println(io, "Test all 256 generated rules against their truth tables.")
    println(io, "For each rule and every possible n-bit input, verifies that each cell's")
    println(io, "output matches the expected ECA truth table lookup.")
    println(io, "\"\"\"")
    println(io, "function test_all_rules(n::Int=8)")
    println(io, "    passed = 0")
    println(io, "    failed = 0")
    println(io)
    println(io, "    for rule in 0:255")
    println(io, "        eca = ECARule(rule, n)")
    println(io, "        rule_ok = true")
    println(io)
    println(io, "        for x_int in 0:(1 << n) - 1")
    println(io, "            x = UInt16(x_int)")
    println(io, "            result = apply(eca, x)")
    println(io)
    println(io, "            for i in 0:(n - 1)")
    println(io, "                l_bit = Int((x >> ((i - 1 + n) % n)) & 1)")
    println(io, "                c_bit = Int((x >> i) & 1)")
    println(io, "                r_bit = Int((x >> ((i + 1) % n)) & 1)")
    println(io)
    println(io, "                index = l_bit * 4 + c_bit * 2 + r_bit")
    println(io, "                expected = (rule >> index) & 1")
    println(io, "                actual = Int((result >> i) & 1)")
    println(io)
    println(io, "                if actual != expected")
    println(io, "                    rule_ok = false")
    println(io, "                    println(\"Rule \$(rule) FAILED: x=\$(bitstring(UInt8(x))),\" *")
    println(io, "                            \" cell \$(i), l=\$(l_bit) c=\$(c_bit) r=\$(r_bit),\" *")
    println(io, "                            \" expected=\$(expected) got=\$(actual)\")")
    println(io, "                    @goto next_rule")
    println(io, "                end")
    println(io, "            end")
    println(io, "        end")
    println(io)
    println(io, "        @label next_rule")
    println(io, "        if rule_ok")
    println(io, "            passed += 1")
    println(io, "        else")
    println(io, "            failed += 1")
    println(io, "        end")
    println(io, "    end")
    println(io)
    println(io, "    println(\"Results: \$(passed) passed, \$(failed) failed out of 256 rules\")")
    println(io, "    return failed == 0")
    println(io, "end")
end

function solve()
    # Terminal states: truth tables that map directly to inputs or constants.
    # Values represent total operation cost (negative = more ops, maximise to minimise ops).
    # L and R cost -3 because shift_left/shift_right each take ~3 bitwise ops.
    # C costs 0 (it's just x). Constants 0x00 and 0xff cost 0 (free constants).
    terminal_state_values = Dict{UInt8, Int}(
        0x00=>0, 0xff=>0, 0xf0=>-3, 0xcc=>0, 0xaa=>-3
    )

    # Precompute available actions: for each truth table state,
    # which operations (on which operand truth tables) produce it
    available_actions = Dict{State, Vector{Action}}()
    for s in state_iterator()
        available_actions[State(s)] = Action[]
    end

    for s1 in state_iterator()
        # NOT: ~s1 can be produced by NOT of s1
        s′ = ~s1
        action = Action(NOT, s1, UInt8(0))
        push!(available_actions[State(s′)], action)

        if s1 == UInt8(255)
            break # avoid overflow on s1 + 1
        end

        # Binary ops: only check s1 < s2 (commutative ops)
        for s2 in state_iterator(s1 + UInt8(1))
            for op_code in (AND, XOR, OR)
                op = operation(op_code)
                s′ = op(s1, s2)
                action = Action(op_code, s1, s2)
                push!(available_actions[State(s′)], action)
            end
        end
    end

    no_action = Action(nothing, UInt8(0), UInt8(0))
    Q = Dict{Tuple{State, Action}, Int}()

    # Set initial Q table: terminal states get their fixed values,
    # non-terminal states get -1 (one operation cost) as initial estimate
    for s in state_iterator()
        current_state = State(s)
        if haskey(terminal_state_values, s)
            # Terminal: only action is "do nothing" at the terminal's base cost
            Q[(current_state, no_action)] = terminal_state_values[s]
            available_actions[current_state] = [no_action]
            continue
        end

        for a in available_actions[current_state]
            Q[(current_state, a)] = -1 # initial action cost
        end
    end

    best_q_value(s::State) = maximum(Q[(s, a)] for a in available_actions[s])

    # Converge to best Q function via value iteration
    iteration = 0
    while true
        has_changed = false
        iteration += 1

        for s in state_iterator()
            haskey(terminal_state_values, s) && continue # skip terminal states

            state = State(s)
            for a in available_actions[state]
                next_value = -1 + best_q_value(State(a.arg1)) # cost of this operation + sub-expr cost
                if !(a.op isa T_NOT)
                    next_value += best_q_value(State(a.arg2))
                end

                if Q[(state, a)] != next_value
                    Q[(state, a)] = next_value
                    has_changed = true
                end
            end
        end

        has_changed || break # converged when no Q values change
    end
    println("Q-function converged after $(iteration) iterations")

    # Visit Q[(s,a)] to find which action to take, then trace back through sub-states.
    # Stop when the action has op == nothing (terminal state).
    # Use uses_input to check which of l, r, c are needed (skip unnecessary shifts).
    # Build a Julia Expr for each rule's apply function.
    function_exprs = Any[]
    body_exprs = Any[]
    for s in state_iterator()
        body = build_rule_expr(State(s), Q, available_actions, terminal_state_values)
        push!(body_exprs, body)
        push!(function_exprs, make_apply_expr(Int(s), body))
    end

    # Write to rules.jl: includes ECARule struct, shift_left/shift_right,
    # all 256 apply methods, and a constructor to pick the right rule by number
    write_rules_file("rules.jl", body_exprs)

    # Test all generated rules by including rules.jl and running test_all_rules()
    println("Testing generated rules...")
    include("rules.jl")
    Base.invokelatest(test_all_rules)

    return function_exprs
end
