# Auto-generated Elementary Cellular Automaton rule implementations
# Generated by eca_dp.jl
#
# Each rule operates on a packed bit array x of type T with N active bits,
# using periodic (circular) boundary conditions via shift_left / shift_right.
#   l = shift_left(x)  — left neighbours  (cell i-1 for each cell i)
#   c = x              — centre cells
#   r = shift_right(x) — right neighbours (cell i+1 for each cell i)

struct ECARule{R, N} end
ECARule(rule::Int, nbits::Int) = ECARule{rule, nbits}()

@inline function shift_left(x::T, ::Val{N}) where {T, N}
    (x << 1) | (x >> (N - 1))
end

@inline function shift_right(x::T, ::Val{N}) where {T, N}
    (x >> 1) | ((x & one(T)) << (N - 1))
end

# Rule 0: zero(T)
@inline function apply(::ECARule{0, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    return m & (zero(T))
end

# Rule 1: ~((r | (c | l)))
@inline function apply(::ECARule{1, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((r | (c | l))))
end

# Rule 2: (~((c | l)) & r)
@inline function apply(::ECARule{2, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c | l)) & r))
end

# Rule 3: ~((c | l))
@inline function apply(::ECARule{3, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & (~((c | l)))
end

# Rule 4: (~((r | l)) & c)
@inline function apply(::ECARule{4, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r | l)) & c))
end

# Rule 5: ~((r | l))
@inline function apply(::ECARule{5, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & (~((r | l)))
end

# Rule 6: (~(l) & xor(r, c))
@inline function apply(::ECARule{6, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) & xor(r, c)))
end

# Rule 7: ~(((r & c) | l))
@inline function apply(::ECARule{7, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~(((r & c) | l)))
end

# Rule 8: ((~(l) & r) & c)
@inline function apply(::ECARule{8, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & r) & c))
end

# Rule 9: ~((xor(r, c) | l))
@inline function apply(::ECARule{9, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(r, c) | l)))
end

# Rule 10: (~(l) & r)
@inline function apply(::ECARule{10, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & ((~(l) & r))
end

# Rule 11: (~(l) & (~(c) | r))
@inline function apply(::ECARule{11, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) & (~(c) | r)))
end

# Rule 12: (~(l) & c)
@inline function apply(::ECARule{12, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & ((~(l) & c))
end

# Rule 13: (~(l) & (~(r) | c))
@inline function apply(::ECARule{13, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) & (~(r) | c)))
end

# Rule 14: (~(l) & (r | c))
@inline function apply(::ECARule{14, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) & (r | c)))
end

# Rule 15: ~(l)
@inline function apply(::ECARule{15, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    return m & (~(l))
end

# Rule 16: (~((r | c)) & l)
@inline function apply(::ECARule{16, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r | c)) & l))
end

# Rule 17: ~((r | c))
@inline function apply(::ECARule{17, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & (~((r | c)))
end

# Rule 18: (~(c) & xor(r, l))
@inline function apply(::ECARule{18, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) & xor(r, l)))
end

# Rule 19: ~(((r & l) | c))
@inline function apply(::ECARule{19, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~(((r & l) | c)))
end

# Rule 20: (xor(c, l) & ~(r))
@inline function apply(::ECARule{20, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) & ~(r)))
end

# Rule 21: ~((r | (c & l)))
@inline function apply(::ECARule{21, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((r | (c & l))))
end

# Rule 22: xor(r, (xor(c, l) | (r & c)))
@inline function apply(::ECARule{22, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(r, (xor(c, l) | (r & c))))
end

# Rule 23: xor((xor(c, l) & xor(r, c)), ~(c))
@inline function apply(::ECARule{23, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & xor(r, c)), ~(c)))
end

# Rule 24: (xor(c, l) & xor(~(c), r))
@inline function apply(::ECARule{24, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) & xor(~(c), r)))
end

# Rule 25: xor(c, (~(r) | (c & l)))
@inline function apply(::ECARule{25, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (~(r) | (c & l))))
end

# Rule 26: xor((r | (c & l)), l)
@inline function apply(::ECARule{26, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((r | (c & l)), l))
end

# Rule 27: xor((xor(c, l) & r), ~(c))
@inline function apply(::ECARule{27, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & r), ~(c)))
end

# Rule 28: (xor(c, l) & (~(r) | c))
@inline function apply(::ECARule{28, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) & (~(r) | c)))
end

# Rule 29: xor((c & l), (~(r) | c))
@inline function apply(::ECARule{29, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((c & l), (~(r) | c)))
end

# Rule 30: xor((r | c), l)
@inline function apply(::ECARule{30, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((r | c), l))
end

# Rule 31: ~(((r | c) & l))
@inline function apply(::ECARule{31, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~(((r | c) & l)))
end

# Rule 32: ((~(c) & r) & l)
@inline function apply(::ECARule{32, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & r) & l))
end

# Rule 33: ~((xor(r, l) | c))
@inline function apply(::ECARule{33, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(r, l) | c)))
end

# Rule 34: (~(c) & r)
@inline function apply(::ECARule{34, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) & r))
end

# Rule 35: (~(c) & (~(l) | r))
@inline function apply(::ECARule{35, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) & (~(l) | r)))
end

# Rule 36: (xor(c, l) & xor(r, c))
@inline function apply(::ECARule{36, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) & xor(r, c)))
end

# Rule 37: xor((~(l) | (r & c)), r)
@inline function apply(::ECARule{37, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) | (r & c)), r))
end

# Rule 38: xor(c, (r | (c & l)))
@inline function apply(::ECARule{38, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (r | (c & l))))
end

# Rule 39: xor(c, (r | xor(~(l), c)))
@inline function apply(::ECARule{39, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (r | xor(~(l), c))))
end

# Rule 40: (xor(c, l) & r)
@inline function apply(::ECARule{40, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) & r))
end

# Rule 41: xor(~(l), xor(c, (r | (c & l))))
@inline function apply(::ECARule{41, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), xor(c, (r | (c & l)))))
end

# Rule 42: (~((c & l)) & r)
@inline function apply(::ECARule{42, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c & l)) & r))
end

# Rule 43: xor(c, (xor(r, c) | xor(~(l), c)))
@inline function apply(::ECARule{43, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (xor(r, c) | xor(~(l), c))))
end

# Rule 44: (xor(c, l) & (r | c))
@inline function apply(::ECARule{44, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) & (r | c)))
end

# Rule 45: xor((~(r) | c), l)
@inline function apply(::ECARule{45, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(r) | c), l))
end

# Rule 46: xor((c & l), (r | c))
@inline function apply(::ECARule{46, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((c & l), (r | c)))
end

# Rule 47: (~(l) | (~(c) & r))
@inline function apply(::ECARule{47, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) | (~(c) & r)))
end

# Rule 48: (~(c) & l)
@inline function apply(::ECARule{48, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & ((~(c) & l))
end

# Rule 49: (~(c) & (~(r) | l))
@inline function apply(::ECARule{49, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) & (~(r) | l)))
end

# Rule 50: (~(c) & (r | l))
@inline function apply(::ECARule{50, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) & (r | l)))
end

# Rule 51: ~(c)
@inline function apply(::ECARule{51, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    return m & (~(c))
end

# Rule 52: xor(c, ((r & c) | l))
@inline function apply(::ECARule{52, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, ((r & c) | l)))
end

# Rule 53: xor(c, (xor(~(c), r) | l))
@inline function apply(::ECARule{53, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (xor(~(c), r) | l)))
end

# Rule 54: xor(c, (r | l))
@inline function apply(::ECARule{54, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (r | l)))
end

# Rule 55: ~((c & (r | l)))
@inline function apply(::ECARule{55, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((c & (r | l))))
end

# Rule 56: (xor(c, l) & (~(c) | r))
@inline function apply(::ECARule{56, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) & (~(c) | r)))
end

# Rule 57: xor(c, (~(r) | l))
@inline function apply(::ECARule{57, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (~(r) | l)))
end

# Rule 58: xor(c, (xor(r, c) | l))
@inline function apply(::ECARule{58, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(c, (xor(r, c) | l)))
end

# Rule 59: ((~(l) & r) | ~(c))
@inline function apply(::ECARule{59, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & r) | ~(c)))
end

# Rule 60: xor(c, l)
@inline function apply(::ECARule{60, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & (xor(c, l))
end

# Rule 61: (~((r | c)) | xor(c, l))
@inline function apply(::ECARule{61, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r | c)) | xor(c, l)))
end

# Rule 62: ((~(c) & r) | xor(c, l))
@inline function apply(::ECARule{62, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & r) | xor(c, l)))
end

# Rule 63: ~((c & l))
@inline function apply(::ECARule{63, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & (~((c & l)))
end

# Rule 64: ((~(r) & c) & l)
@inline function apply(::ECARule{64, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(r) & c) & l))
end

# Rule 65: ~((xor(c, l) | r))
@inline function apply(::ECARule{65, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(c, l) | r)))
end

# Rule 66: (xor(r, c) & xor(~(l), c))
@inline function apply(::ECARule{66, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) & xor(~(l), c)))
end

# Rule 67: xor((~(l) | (r & c)), c)
@inline function apply(::ECARule{67, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) | (r & c)), c))
end

# Rule 68: (~(r) & c)
@inline function apply(::ECARule{68, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(r) & c))
end

# Rule 69: (~(r) & (~(l) | c))
@inline function apply(::ECARule{69, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(r) & (~(l) | c)))
end

# Rule 70: (xor(r, c) & (~(l) | c))
@inline function apply(::ECARule{70, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) & (~(l) | c)))
end

# Rule 71: xor((r & c), (~(l) | c))
@inline function apply(::ECARule{71, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((r & c), (~(l) | c)))
end

# Rule 72: (xor(r, l) & c)
@inline function apply(::ECARule{72, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, l) & c))
end

# Rule 73: xor(~(l), (xor(r, c) & (~(l) | c)))
@inline function apply(::ECARule{73, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), (xor(r, c) & (~(l) | c))))
end

# Rule 74: (xor(r, l) & (r | c))
@inline function apply(::ECARule{74, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, l) & (r | c)))
end

# Rule 75: xor((~(c) | r), l)
@inline function apply(::ECARule{75, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(c) | r), l))
end

# Rule 76: (~((r & l)) & c)
@inline function apply(::ECARule{76, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r & l)) & c))
end

# Rule 77: xor(~(c), (xor(c, l) | xor(r, c)))
@inline function apply(::ECARule{77, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), (xor(c, l) | xor(r, c))))
end

# Rule 78: xor((r & xor(~(l), c)), c)
@inline function apply(::ECARule{78, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((r & xor(~(l), c)), c))
end

# Rule 79: (~(l) | (~(r) & c))
@inline function apply(::ECARule{79, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) | (~(r) & c)))
end

# Rule 80: (~(r) & l)
@inline function apply(::ECARule{80, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & ((~(r) & l))
end

# Rule 81: (~(r) & (~(c) | l))
@inline function apply(::ECARule{81, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(r) & (~(c) | l)))
end

# Rule 82: xor(r, ((r & c) | l))
@inline function apply(::ECARule{82, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(r, ((r & c) | l)))
end

# Rule 83: xor(~(c), (xor(r, c) & l))
@inline function apply(::ECARule{83, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), (xor(r, c) & l)))
end

# Rule 84: (~(r) & (c | l))
@inline function apply(::ECARule{84, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(r) & (c | l)))
end

# Rule 85: ~(r)
@inline function apply(::ECARule{85, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    r = shift_right(x, Val(N))
    return m & (~(r))
end

# Rule 86: xor(r, (c | l))
@inline function apply(::ECARule{86, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(r, (c | l)))
end

# Rule 87: ~((r & (c | l)))
@inline function apply(::ECARule{87, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((r & (c | l))))
end

# Rule 88: (xor(r, l) & (c | l))
@inline function apply(::ECARule{88, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, l) & (c | l)))
end

# Rule 89: xor(r, (~(c) | l))
@inline function apply(::ECARule{89, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(r, (~(c) | l)))
end

# Rule 90: xor(r, l)
@inline function apply(::ECARule{90, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & (xor(r, l))
end

# Rule 91: (~((c | l)) | xor(r, l))
@inline function apply(::ECARule{91, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c | l)) | xor(r, l)))
end

# Rule 92: xor((xor(~(c), r) & l), c)
@inline function apply(::ECARule{92, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(~(c), r) & l), c))
end

# Rule 93: ((~(l) & c) | ~(r))
@inline function apply(::ECARule{93, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & c) | ~(r)))
end

# Rule 94: ((~(l) & c) | xor(r, l))
@inline function apply(::ECARule{94, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & c) | xor(r, l)))
end

# Rule 95: ~((r & l))
@inline function apply(::ECARule{95, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & (~((r & l)))
end

# Rule 96: (xor(r, c) & l)
@inline function apply(::ECARule{96, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) & l))
end

# Rule 97: xor(~(((r & c) | l)), xor(r, c))
@inline function apply(::ECARule{97, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(((r & c) | l)), xor(r, c)))
end

# Rule 98: (xor(r, c) & (~(c) | l))
@inline function apply(::ECARule{98, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) & (~(c) | l)))
end

# Rule 99: xor((~(l) | r), c)
@inline function apply(::ECARule{99, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) | r), c))
end

# Rule 100: (xor(r, c) & (c | l))
@inline function apply(::ECARule{100, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) & (c | l)))
end

# Rule 101: xor(r, (~(l) | c))
@inline function apply(::ECARule{101, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(r, (~(l) | c)))
end

# Rule 102: xor(r, c)
@inline function apply(::ECARule{102, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(r, c))
end

# Rule 103: (~((c | l)) | xor(r, c))
@inline function apply(::ECARule{103, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c | l)) | xor(r, c)))
end

# Rule 104: (xor(r, (c & l)) & (c | l))
@inline function apply(::ECARule{104, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, (c & l)) & (c | l)))
end

# Rule 105: xor(~(l), xor(r, c))
@inline function apply(::ECARule{105, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), xor(r, c)))
end

# Rule 106: xor(r, (c & l))
@inline function apply(::ECARule{106, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(r, (c & l)))
end

# Rule 107: (~((c | l)) | xor(r, (c & l)))
@inline function apply(::ECARule{107, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c | l)) | xor(r, (c & l))))
end

# Rule 108: xor((r & l), c)
@inline function apply(::ECARule{108, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((r & l), c))
end

# Rule 109: xor((~(l) & (~(c) | r)), xor(r, c))
@inline function apply(::ECARule{109, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & (~(c) | r)), xor(r, c)))
end

# Rule 110: ((~(l) & c) | xor(r, c))
@inline function apply(::ECARule{110, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & c) | xor(r, c)))
end

# Rule 111: (~(l) | xor(r, c))
@inline function apply(::ECARule{111, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) | xor(r, c)))
end

# Rule 112: (~((r & c)) & l)
@inline function apply(::ECARule{112, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r & c)) & l))
end

# Rule 113: xor((xor(c, l) | xor(~(c), r)), c)
@inline function apply(::ECARule{113, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) | xor(~(c), r)), c))
end

# Rule 114: xor((xor(c, l) | r), c)
@inline function apply(::ECARule{114, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) | r), c))
end

# Rule 115: (~(c) | (~(r) & l))
@inline function apply(::ECARule{115, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) | (~(r) & l)))
end

# Rule 116: xor((r & c), (c | l))
@inline function apply(::ECARule{116, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((r & c), (c | l)))
end

# Rule 117: ((~(c) & l) | ~(r))
@inline function apply(::ECARule{117, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & l) | ~(r)))
end

# Rule 118: ((~(c) & l) | xor(r, c))
@inline function apply(::ECARule{118, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & l) | xor(r, c)))
end

# Rule 119: ~((r & c))
@inline function apply(::ECARule{119, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & (~((r & c)))
end

# Rule 120: xor((r & c), l)
@inline function apply(::ECARule{120, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((r & c), l))
end

# Rule 121: (~((r | c)) | xor((r & c), l))
@inline function apply(::ECARule{121, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r | c)) | xor((r & c), l)))
end

# Rule 122: ((~(c) & r) | xor(r, l))
@inline function apply(::ECARule{122, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & r) | xor(r, l)))
end

# Rule 123: (~(c) | xor(r, l))
@inline function apply(::ECARule{123, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) | xor(r, l)))
end

# Rule 124: (xor(c, l) | (~(r) & c))
@inline function apply(::ECARule{124, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) | (~(r) & c)))
end

# Rule 125: (xor(c, l) | ~(r))
@inline function apply(::ECARule{125, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) | ~(r)))
end

# Rule 126: (xor(c, l) | xor(r, c))
@inline function apply(::ECARule{126, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) | xor(r, c)))
end

# Rule 127: ~(((r & c) & l))
@inline function apply(::ECARule{127, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~(((r & c) & l)))
end

# Rule 128: ((r & c) & l)
@inline function apply(::ECARule{128, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((r & c) & l))
end

# Rule 129: ~((xor(c, l) | xor(r, c)))
@inline function apply(::ECARule{129, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(c, l) | xor(r, c))))
end

# Rule 130: (r & xor(~(l), c))
@inline function apply(::ECARule{130, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((r & xor(~(l), c)))
end

# Rule 131: xor(~(c), ((~(c) | r) & l))
@inline function apply(::ECARule{131, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), ((~(c) | r) & l)))
end

# Rule 132: xor((xor(r, l) & c), c)
@inline function apply(::ECARule{132, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(r, l) & c), c))
end

# Rule 133: xor(~(l), (r & (~(l) | c)))
@inline function apply(::ECARule{133, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), (r & (~(l) | c))))
end

# Rule 134: xor((xor(c, l) & (r | c)), r)
@inline function apply(::ECARule{134, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & (r | c)), r))
end

# Rule 135: xor(~(l), (r & c))
@inline function apply(::ECARule{135, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), (r & c)))
end

# Rule 136: (r & c)
@inline function apply(::ECARule{136, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & ((r & c))
end

# Rule 137: xor(~(c), ((~(c) & l) | r))
@inline function apply(::ECARule{137, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), ((~(c) & l) | r)))
end

# Rule 138: (r & (~(l) | c))
@inline function apply(::ECARule{138, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((r & (~(l) | c)))
end

# Rule 139: xor(~((c | l)), (r & c))
@inline function apply(::ECARule{139, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((c | l)), (r & c)))
end

# Rule 140: ((~(l) | r) & c)
@inline function apply(::ECARule{140, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) | r) & c))
end

# Rule 141: xor(~(c), (xor(c, l) | r))
@inline function apply(::ECARule{141, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), (xor(c, l) | r)))
end

# Rule 142: xor((xor(r, c) & xor(~(l), c)), c)
@inline function apply(::ECARule{142, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(r, c) & xor(~(l), c)), c))
end

# Rule 143: (~(l) | (r & c))
@inline function apply(::ECARule{143, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) | (r & c)))
end

# Rule 144: (xor(~(c), r) & l)
@inline function apply(::ECARule{144, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(~(c), r) & l))
end

# Rule 145: xor(~(c), (r & (~(c) | l)))
@inline function apply(::ECARule{145, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), (r & (~(c) | l))))
end

# Rule 146: xor((xor(c, l) & (~(c) | r)), r)
@inline function apply(::ECARule{146, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & (~(c) | r)), r))
end

# Rule 147: xor(~(c), (r & l))
@inline function apply(::ECARule{147, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), (r & l)))
end

# Rule 148: xor(xor(c, l), (r & (c | l)))
@inline function apply(::ECARule{148, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(xor(c, l), (r & (c | l))))
end

# Rule 149: xor(~((c & l)), r)
@inline function apply(::ECARule{149, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((c & l)), r))
end

# Rule 150: xor(xor(c, l), r)
@inline function apply(::ECARule{150, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(xor(c, l), r))
end

# Rule 151: (~((c | l)) | xor(xor(c, l), r))
@inline function apply(::ECARule{151, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c | l)) | xor(xor(c, l), r)))
end

# Rule 152: xor((~(r) & (c | l)), c)
@inline function apply(::ECARule{152, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(r) & (c | l)), c))
end

# Rule 153: xor(~(c), r)
@inline function apply(::ECARule{153, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), r))
end

# Rule 154: xor((~(c) & l), r)
@inline function apply(::ECARule{154, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(c) & l), r))
end

# Rule 155: xor(~(c), (r & (c | l)))
@inline function apply(::ECARule{155, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(c), (r & (c | l))))
end

# Rule 156: xor((~(r) & l), c)
@inline function apply(::ECARule{156, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(r) & l), c))
end

# Rule 157: ((~(l) & c) | xor(~(c), r))
@inline function apply(::ECARule{157, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & c) | xor(~(c), r)))
end

# Rule 158: (xor((r | c), l) | (r & c))
@inline function apply(::ECARule{158, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor((r | c), l) | (r & c)))
end

# Rule 159: ~((xor(r, c) & l))
@inline function apply(::ECARule{159, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(r, c) & l)))
end

# Rule 160: (r & l)
@inline function apply(::ECARule{160, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & ((r & l))
end

# Rule 161: xor((~(l) & (~(c) | r)), r)
@inline function apply(::ECARule{161, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & (~(c) | r)), r))
end

# Rule 162: (r & (~(c) | l))
@inline function apply(::ECARule{162, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((r & (~(c) | l)))
end

# Rule 163: xor((~(l) | xor(r, c)), c)
@inline function apply(::ECARule{163, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) | xor(r, c)), c))
end

# Rule 164: xor((~(l) & (r | c)), r)
@inline function apply(::ECARule{164, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & (r | c)), r))
end

# Rule 165: xor(~(l), r)
@inline function apply(::ECARule{165, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & (xor(~(l), r))
end

# Rule 166: xor((~(l) & c), r)
@inline function apply(::ECARule{166, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & c), r))
end

# Rule 167: xor(~(l), (r & (c | l)))
@inline function apply(::ECARule{167, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), (r & (c | l))))
end

# Rule 168: (r & (c | l))
@inline function apply(::ECARule{168, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((r & (c | l)))
end

# Rule 169: xor(~((c | l)), r)
@inline function apply(::ECARule{169, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((c | l)), r))
end

# Rule 170: r
@inline function apply(::ECARule{170, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    r = shift_right(x, Val(N))
    return m & (r)
end

# Rule 171: (~((c | l)) | r)
@inline function apply(::ECARule{171, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c | l)) | r))
end

# Rule 172: xor((xor(r, c) & l), c)
@inline function apply(::ECARule{172, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(r, c) & l), c))
end

# Rule 173: xor(~(((r & c) | l)), r)
@inline function apply(::ECARule{173, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(((r & c) | l)), r))
end

# Rule 174: ((~(l) & c) | r)
@inline function apply(::ECARule{174, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & c) | r))
end

# Rule 175: (~(l) | r)
@inline function apply(::ECARule{175, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & ((~(l) | r))
end

# Rule 176: ((~(c) | r) & l)
@inline function apply(::ECARule{176, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) | r) & l))
end

# Rule 177: xor((xor(c, l) | ~(r)), c)
@inline function apply(::ECARule{177, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) | ~(r)), c))
end

# Rule 178: xor((xor(c, l) | xor(r, c)), c)
@inline function apply(::ECARule{178, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) | xor(r, c)), c))
end

# Rule 179: (~(c) | (r & l))
@inline function apply(::ECARule{179, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) | (r & l)))
end

# Rule 180: xor(xor(c, l), (r & c))
@inline function apply(::ECARule{180, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(xor(c, l), (r & c)))
end

# Rule 181: xor(~(((r | c) & l)), r)
@inline function apply(::ECARule{181, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(((r | c) & l)), r))
end

# Rule 182: xor((xor(c, l) & (~(r) | c)), r)
@inline function apply(::ECARule{182, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & (~(r) | c)), r))
end

# Rule 183: ~((xor(r, l) & c))
@inline function apply(::ECARule{183, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(r, l) & c)))
end

# Rule 184: xor((~(c) & l), (r & c))
@inline function apply(::ECARule{184, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(c) & l), (r & c)))
end

# Rule 185: ((~(c) & l) | xor(~(c), r))
@inline function apply(::ECARule{185, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & l) | xor(~(c), r)))
end

# Rule 186: ((~(c) & l) | r)
@inline function apply(::ECARule{186, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & l) | r))
end

# Rule 187: (~(c) | r)
@inline function apply(::ECARule{187, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) | r))
end

# Rule 188: (xor(c, l) | (r & c))
@inline function apply(::ECARule{188, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) | (r & c)))
end

# Rule 189: (xor(c, l) | xor(~(c), r))
@inline function apply(::ECARule{189, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) | xor(~(c), r)))
end

# Rule 190: (xor(c, l) | r)
@inline function apply(::ECARule{190, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(c, l) | r))
end

# Rule 191: (~((c & l)) | r)
@inline function apply(::ECARule{191, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((c & l)) | r))
end

# Rule 192: (c & l)
@inline function apply(::ECARule{192, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & ((c & l))
end

# Rule 193: xor((~(l) & (~(r) | c)), c)
@inline function apply(::ECARule{193, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & (~(r) | c)), c))
end

# Rule 194: xor((~(l) & (r | c)), c)
@inline function apply(::ECARule{194, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & (r | c)), c))
end

# Rule 195: xor(~(l), c)
@inline function apply(::ECARule{195, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & (xor(~(l), c))
end

# Rule 196: (c & (~(r) | l))
@inline function apply(::ECARule{196, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((c & (~(r) | l)))
end

# Rule 197: xor(~((xor(r, c) | l)), c)
@inline function apply(::ECARule{197, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((xor(r, c) | l)), c))
end

# Rule 198: xor((~(l) & r), c)
@inline function apply(::ECARule{198, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & r), c))
end

# Rule 199: xor((~(l) & (~(c) | r)), c)
@inline function apply(::ECARule{199, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & (~(c) | r)), c))
end

# Rule 200: (c & (r | l))
@inline function apply(::ECARule{200, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((c & (r | l)))
end

# Rule 201: xor(~((r | l)), c)
@inline function apply(::ECARule{201, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((r | l)), c))
end

# Rule 202: xor((~(l) & xor(r, c)), c)
@inline function apply(::ECARule{202, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & xor(r, c)), c))
end

# Rule 203: xor(~(((r & c) | l)), c)
@inline function apply(::ECARule{203, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(((r & c) | l)), c))
end

# Rule 204: c
@inline function apply(::ECARule{204, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    return m & (c)
end

# Rule 205: (~((r | l)) | c)
@inline function apply(::ECARule{205, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r | l)) | c))
end

# Rule 206: ((~(l) & r) | c)
@inline function apply(::ECARule{206, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(l) & r) | c))
end

# Rule 207: (~(l) | c)
@inline function apply(::ECARule{207, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & ((~(l) | c))
end

# Rule 208: ((~(r) | c) & l)
@inline function apply(::ECARule{208, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(r) | c) & l))
end

# Rule 209: xor(~((r | c)), (c & l))
@inline function apply(::ECARule{209, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((r | c)), (c & l)))
end

# Rule 210: xor(xor((r | c), l), c)
@inline function apply(::ECARule{210, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(xor((r | c), l), c))
end

# Rule 211: xor(~(((r | c) & l)), c)
@inline function apply(::ECARule{211, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(((r | c) & l)), c))
end

# Rule 212: xor((xor(c, l) & xor(~(c), r)), c)
@inline function apply(::ECARule{212, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & xor(~(c), r)), c))
end

# Rule 213: (~(r) | (c & l))
@inline function apply(::ECARule{213, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(r) | (c & l)))
end

# Rule 214: xor(xor((r | (c & l)), l), c)
@inline function apply(::ECARule{214, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(xor((r | (c & l)), l), c))
end

# Rule 215: ~((xor(c, l) & r))
@inline function apply(::ECARule{215, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(c, l) & r)))
end

# Rule 216: xor((xor(c, l) & ~(r)), c)
@inline function apply(::ECARule{216, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & ~(r)), c))
end

# Rule 217: xor(~((r | (c & l))), c)
@inline function apply(::ECARule{217, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((r | (c & l))), c))
end

# Rule 218: (xor(r, l) | (r & c))
@inline function apply(::ECARule{218, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, l) | (r & c)))
end

# Rule 219: ~((xor(c, l) & xor(r, c)))
@inline function apply(::ECARule{219, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(c, l) & xor(r, c))))
end

# Rule 220: ((~(r) & l) | c)
@inline function apply(::ECARule{220, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(r) & l) | c))
end

# Rule 221: (~(r) | c)
@inline function apply(::ECARule{221, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(r) | c))
end

# Rule 222: (xor(r, l) | c)
@inline function apply(::ECARule{222, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, l) | c))
end

# Rule 223: (~((r & l)) | c)
@inline function apply(::ECARule{223, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r & l)) | c))
end

# Rule 224: ((r | c) & l)
@inline function apply(::ECARule{224, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((r | c) & l))
end

# Rule 225: xor(~(l), (r | c))
@inline function apply(::ECARule{225, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), (r | c)))
end

# Rule 226: xor((~(l) & c), (r | c))
@inline function apply(::ECARule{226, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((~(l) & c), (r | c)))
end

# Rule 227: ~((xor(c, l) & (~(r) | c)))
@inline function apply(::ECARule{227, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (~((xor(c, l) & (~(r) | c))))
end

# Rule 228: xor((xor(c, l) & r), c)
@inline function apply(::ECARule{228, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & r), c))
end

# Rule 229: xor(~(l), (r | (c & l)))
@inline function apply(::ECARule{229, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~(l), (r | (c & l))))
end

# Rule 230: (xor(r, c) | (c & l))
@inline function apply(::ECARule{230, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) | (c & l)))
end

# Rule 231: (xor(r, c) | xor(~(l), c))
@inline function apply(::ECARule{231, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) | xor(~(l), c)))
end

# Rule 232: xor((xor(c, l) & xor(r, c)), c)
@inline function apply(::ECARule{232, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor((xor(c, l) & xor(r, c)), c))
end

# Rule 233: xor(~((c | l)), (r | (c & l)))
@inline function apply(::ECARule{233, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (xor(~((c | l)), (r | (c & l))))
end

# Rule 234: (r | (c & l))
@inline function apply(::ECARule{234, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((r | (c & l)))
end

# Rule 235: (r | xor(~(l), c))
@inline function apply(::ECARule{235, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((r | xor(~(l), c)))
end

# Rule 236: ((r & l) | c)
@inline function apply(::ECARule{236, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((r & l) | c))
end

# Rule 237: (xor(~(l), r) | c)
@inline function apply(::ECARule{237, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(~(l), r) | c))
end

# Rule 238: (r | c)
@inline function apply(::ECARule{238, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    c = x
    r = shift_right(x, Val(N))
    return m & ((r | c))
end

# Rule 239: (~(l) | (r | c))
@inline function apply(::ECARule{239, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(l) | (r | c)))
end

# Rule 240: l
@inline function apply(::ECARule{240, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    return m & (l)
end

# Rule 241: (~((r | c)) | l)
@inline function apply(::ECARule{241, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r | c)) | l))
end

# Rule 242: ((~(c) & r) | l)
@inline function apply(::ECARule{242, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(c) & r) | l))
end

# Rule 243: (~(c) | l)
@inline function apply(::ECARule{243, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & ((~(c) | l))
end

# Rule 244: ((~(r) & c) | l)
@inline function apply(::ECARule{244, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((~(r) & c) | l))
end

# Rule 245: (~(r) | l)
@inline function apply(::ECARule{245, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & ((~(r) | l))
end

# Rule 246: (xor(r, c) | l)
@inline function apply(::ECARule{246, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(r, c) | l))
end

# Rule 247: (~((r & c)) | l)
@inline function apply(::ECARule{247, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~((r & c)) | l))
end

# Rule 248: ((r & c) | l)
@inline function apply(::ECARule{248, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & (((r & c) | l))
end

# Rule 249: (xor(~(c), r) | l)
@inline function apply(::ECARule{249, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((xor(~(c), r) | l))
end

# Rule 250: (r | l)
@inline function apply(::ECARule{250, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    r = shift_right(x, Val(N))
    return m & ((r | l))
end

# Rule 251: (~(c) | (r | l))
@inline function apply(::ECARule{251, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(c) | (r | l)))
end

# Rule 252: (c | l)
@inline function apply(::ECARule{252, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    return m & ((c | l))
end

# Rule 253: (~(r) | (c | l))
@inline function apply(::ECARule{253, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((~(r) | (c | l)))
end

# Rule 254: (r | (c | l))
@inline function apply(::ECARule{254, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    l = shift_left(x, Val(N))
    c = x
    r = shift_right(x, Val(N))
    return m & ((r | (c | l)))
end

# Rule 255: m
@inline function apply(::ECARule{255, N}, x::T) where {N, T}
    m = ~(~zero(T) << N)
    return m & (m)
end

"""
    test_all_rules(n=8) → Bool

Test all 256 generated rules against their truth tables.
For each rule and every possible n-bit input, verifies that each cell's
output matches the expected ECA truth table lookup.
"""
function test_all_rules(n::Int=8)
    passed = 0
    failed = 0

    for rule in 0:255
        eca = ECARule(rule, n)
        rule_ok = true

        for x_int in 0:(1 << n) - 1
            x = UInt16(x_int)
            result = apply(eca, x)

            for i in 0:(n - 1)
                l_bit = Int((x >> ((i - 1 + n) % n)) & 1)
                c_bit = Int((x >> i) & 1)
                r_bit = Int((x >> ((i + 1) % n)) & 1)

                index = l_bit * 4 + c_bit * 2 + r_bit
                expected = (rule >> index) & 1
                actual = Int((result >> i) & 1)

                if actual != expected
                    rule_ok = false
                    println("Rule $(rule) FAILED: x=$(bitstring(UInt8(x)))," *
                            " cell $(i), l=$(l_bit) c=$(c_bit) r=$(r_bit)," *
                            " expected=$(expected) got=$(actual)")
                    @goto next_rule
                end
            end
        end

        @label next_rule
        if rule_ok
            passed += 1
        else
            failed += 1
        end
    end

    println("Results: $(passed) passed, $(failed) failed out of 256 rules")
    return failed == 0
end
